import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { io } from "socket.io-client";
import { useState, useEffect, useRef } from "react";

export default function Home() {
  const [value, setValue] = useState(0);
  const socketRef = useRef();

  useEffect(() => {
    socketRef.current = io(process.env.SOCKET_SERVER_URL, {
      path: "/api/socket",
    });

    socketRef.current.on("connect", () => {
      console.log("SOCKET CONNECTED!", socketRef.current.id);
    });

    socketRef.current.on("changeValue", (newValue) => {
      setValue(newValue);
      console.log(`Valor actualizado a: ${newValue}`);
    });

    socketRef.current.on("updateValue", (newValue) => {
      setValue(newValue);
      console.log(`Valor actualizado a: ${newValue}`);
    });

    return () => {
      socketRef.current.disconnect();
    };
  }, []);

  const handleChangeValue = (newValue) => {
    socketRef.current.emit("changeValue", newValue);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{ color: "white" }}>Valor compartido: {value}</h1>
      <button onClick={() => handleChangeValue(prompt("Add the value"))}>
        Actualizar Valor
      </button>
    </>
  );
}


